; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61030.0 

	TITLE	E:\Dokumenty Koziol\GRZEGORZ\Dysk Google\Grzesiek\Dokumenty\STUDIA\JA\Projekt\Hasla\DLLC\File.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_startTime
PUBLIC	_endTime
PUBLIC	_resultTime
PUBLIC	_endTimefull
PUBLIC	_startTimefull
PUBLIC	_CPUInfo
PUBLIC	_bSSE41Extensions
PUBLIC	_bSSE42Extensions
PUBLIC	_nLogicalProcessors
PUBLIC	_nFeatureInfo
PUBLIC	_bMultithreading
_DATA	SEGMENT
COMM	___@@_PchSym_@00@UwlpfnvmgbLplarloUtiavtliaUwbhpLtlltovUtiavhrvpUwlpfnvmgbUhgfwrzUqzUkilqvpgUszhozUwooxUwvyftUhgwzucOlyq@7523FF6FB403CA84:DWORD
_DATA	ENDS
_BSS	SEGMENT
_startTime DD	01H DUP (?)
_endTime DD	01H DUP (?)
_resultTime DD	01H DUP (?)
_endTimefull DD	01H DUP (?)
_startTimefull DD 01H DUP (?)
_bSSE41Extensions DB 01H DUP (?)
	ALIGN	4

_bSSE42Extensions DB 01H DUP (?)
	ALIGN	4

_nLogicalProcessors DD 01H DUP (?)
_nFeatureInfo DD 01H DUP (?)
_bMultithreading DB 01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
_CPUInfo DD	0ffffffffH
	ORG $+12
_DATA	ENDS
PUBLIC	_openFileAndGetNumberOfElements
PUBLIC	??_C@_01KDCPPGHE@r?$AA@				; `string'
EXTRN	__imp__fgets:PROC
EXTRN	__imp__fopen:PROC
EXTRN	__imp__atoi:PROC
EXTRN	__imp__free:PROC
EXTRN	__imp__malloc:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_01KDCPPGHE@r?$AA@
CONST	SEGMENT
??_C@_01KDCPPGHE@r?$AA@ DB 'r', 00H			; `string'
CONST	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _openFileAndGetNumberOfElements
_TEXT	SEGMENT
_chartmp$1 = -20					; size = 4
_tmp$ = -8						; size = 4
_name$ = 8						; size = 4
_numberofentries$ = 12					; size = 4
_openFileAndGetNumberOfElements PROC			; COMDAT
; File e:\dokumenty koziol\grzegorz\dysk google\grzesiek\dokumenty\studia\ja\projekt\hasla\dllc\file.c
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 6
	mov	esi, esp
	push	OFFSET ??_C@_01KDCPPGHE@r?$AA@
	mov	eax, DWORD PTR _name$[ebp]
	push	eax
	call	DWORD PTR __imp__fopen
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _tmp$[ebp], eax
; Line 8
	cmp	DWORD PTR _tmp$[ebp], 0
	je	SHORT $LN1@openFileAn
; Line 10
	mov	esi, esp
	push	32					; 00000020H
	call	DWORD PTR __imp__malloc
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _chartmp$1[ebp], eax
; Line 11
	mov	esi, esp
	mov	eax, DWORD PTR _tmp$[ebp]
	push	eax
	push	32					; 00000020H
	mov	ecx, DWORD PTR _chartmp$1[ebp]
	push	ecx
	call	DWORD PTR __imp__fgets
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp__atoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	edx, DWORD PTR _numberofentries$[ebp]
	mov	DWORD PTR [edx], eax
; Line 12
	mov	esi, esp
	mov	eax, DWORD PTR _chartmp$1[ebp]
	push	eax
	call	DWORD PTR __imp__free
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN1@openFileAn:
; Line 14
	mov	eax, DWORD PTR _tmp$[ebp]
; Line 15
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_openFileAndGetNumberOfElements ENDP
_TEXT	ENDS
END
