; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.60315.1 

	TITLE	C:\Users\Grzegorz\Desktop\Hasla\DLLC\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
COMM	___@@_PchSym_@00@UfhvihUtiavtliaUwvhpglkUszhozUwooxUwvyftUhgwzucOlyq@EA822F409524E031:DWORD
_DATA	ENDS
END
